POST http://localhost:3001/api/sessions/
Content-Type: application/json

{
	"day": "8th May 2024",
	"session": "⁠12:00PM - 12:40PM: 感恩艺术静心 Art of Gratitude Meditation",
	"maxParticipants": 10
}

###

POST http://localhost:3001/api/sessions/
Content-Type: application/json

{
	"day": "8th May 2024",
	"session": "12:50PM - 1:20PM: 聆听艺术静心 Art of Listening Meditation",
	"maxParticipants": 10
}

###

POST http://localhost:3001/api/sessions/
Content-Type: application/json

{
	"day": "8th May 2024",
	"session": "1:30PM - 2:10PM: 意图力量静心 Art of Intention Meditation",
	"maxParticipants": 10
}

###

POST http://localhost:3001/api/sessions/
Content-Type: application/json

{
	"day": "8th May 2024",
	"session": "⁠⁠2:20PM - 3:00PM: 宽恕艺术静心Art of Forgiveness Meditation",
	"maxParticipants": 10
}
