POST http://localhost:3001/api/participants 
Content-Type: application/json

{
  "name": "Seng Fan Fan",
	"studentId": "23WKP18190",
  "contactNo": "11133472188",
  "email": "ericbongchengliang@gmail.com",
  "gender": "Female",
  "age": 22,
  "day": "8th May 2024",
  "session": "662684250aacfcc6bf45ea4e"
}
