POST http://localhost:3000/api/makeupparticipants 
Content-Type: application/json

{
  "name": "Seng Fan Fan",
	"studentId": "23WKP18190",
  "contactNo": "11133472188",
  "email": "ericbongchengliang@gmail.com",
  "gender": "Female",
  "age": 22,
  "day": "7th May 2024",
  "session": "662e6b5d3f1f0404cbd27f44"
}
