POST http://localhost:3001/api/participants 
Content-Type: application/json
{
	"name": "Eric", 
	"contactNo": "01133472177",
	"email": "ericbong6868@gmail.com",
	"gender": "male",
	"age": 22,
	"remarks": "option 1"
}