GET http://localhost:3001/api/participants
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI2NjI3ODNiNDhlNWExMGRkMzNjMDI3NDEiLCJpYXQiOjE3MTM4ODk3MzR9.ON-AeE0WCwzHrtLMC0tHzJrnZxc849eGhXx8VTtcPlc